name: Update Profile Messages

on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo "## Messages from Visitors" > temp.md
          echo "" >> temp.md
          echo "- ${{ github.event.issue.body }}" >> temp.md
          cat README.md >> temp.md
          mv temp.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Add message from issue #${{ github.event.issue.number }}"
          git push
