name: Update Profile README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repositories List
        uses: actions/github-script@v6
        with:
          script: |
            const username = 'YOUR_USERNAME';
            const repos = await github.repos.listForUser({
              username,
              sort: 'updated',
              per_page: 100,
            });

            const repoList = repos.data.map(repo => 
              `- [${repo.name}](${repo.html_url}): ${repo.description || 'No description provided.'}`
            ).join('\n');

            const readmeContent = `
# Hi, I'm ${username}! 👋

Welcome to my GitHub profile! Here's an overview of my repositories:

## My Projects

${repoList}

*This overview is updated daily by a GitHub Actions workflow.*
`;

            const { data: existingReadme } = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
            });

            await github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update README with latest repositories',
              content: Buffer.from(readmeContent).toString('base64'),
              sha: existingReadme.sha,
            });
