name: Update Profile README

on:
  issues:
    types: [opened] # Trigger on new issues
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Fetch repository list
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.GITHUB_TOKEN }}

      # Read existing README content
      - name: Read Existing README
        id: read-readme
        run: |
          if [ -f README.md ]; then
            cat README.md > existing_readme.md
          else
            echo "## Messages from Visitors\n\nNo messages yet!" > existing_readme.md
          fi

      # Extract Visitor Messages
      - name: Extract Visitor Messages
        id: extract-messages
        run: |
          if grep -q "## Messages from Visitors" existing_readme.md; then
            sed -n '/## Messages from Visitors/,$p' existing_readme.md > visitor_messages.md
          else
            echo "## Messages from Visitors\n\nNo messages yet!" > visitor_messages.md
          fi

      # Construct New README
      - name: Update README
        run: |
          echo "# Hi, I'm YOUR_USERNAME! 👋" > README.md
          echo "" >> README.md
          echo "Welcome to my GitHub profile! Here's an overview of my repositories:" >> README.md
          echo "" >> README.md
          echo "## My Projects" >> README.md
          echo "" >> README.md
          echo "${{ steps.repo.outputs.repoList }}" >> README.md
          echo "" >> README.md
          cat visitor_messages.md >> README.md
          echo "" >> README.md
          echo "# Leave a Message for My Profile!" >> README.md
          echo "" >> README.md
          echo "Want your message featured on this page? [Submit your message here](https://LXBUGR.github.io/LXBUGR/write_message.html)." >> README.md

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with repositories and visitor messages"
          git push
