name: Update Profile README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Use Repo-List-Generator to fetch repositories
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.REPO_TOKEN }} # Optional, only needed for private repos

      # Update README with the repository list
      - name: Update README
        run: |
          echo "# Hi, I'm Alex! 👋" > README.md
          echo "" >> README.md
          echo "## My Projects" >> README.md
          echo "" >> README.md
          echo "${{ steps.repo.outputs.repoList }}" >> README.md
          echo "" >> README.md
          echo "*This overview is updated daily.*" >> README.md

      # Commit and push the changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with repository list"
          git push
